### ISSUE TITLE
Stability tracking issue for pistoncore-input

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1293]
- [x] event_id::EventId
- [x] event_id::AFTER_RENDER
- [x] event_id::CONTROLLER_AXIS
- [x] event_id::CURSOR
- [x] event_id::FOCUS
- [x] event_id::CLOSE
- [x] event_id::IDLE
- [x] event_id::MOUSE_SCROLL
- [x] event_id::MOUSE_RELATIVE
- [x] event_id::MOUSE_CURSOR
- [x] event_id::BUTTON
- [x] event_id::RENDER
- [x] event_id::RESIZE
- [x] event_id::TEXT
- [x] event_id::TOUCH
- [x] event_id::UPDATE
- [x] event_id::FILE_DRAG
- [x] Button
- [x] Motion
- [x] HatState
- [x] FileDrag
- [x] Input
- [x] Loop
- [x] Event
- [x] AfterRenderArgs
- [x] AfterRenderEvent
- [x] ButtonState
- [x] ButtonArgs
- [x] ButtonEvent
- [x] PressEvent
- [x] ReleaseEvent
- [x] CloseArgs
- [x] CloseEvent
- [x] ControllerButton
- [x] ControllerHat
- [x] ControllerAxisArgs
- [x] ControllerAxisEvent
- [x] CursorEvent
- [x] FocusEvent
- [x] GenericEvent
- [x] IdleArgs
- [x] IdleEvent
- [x] ModifierKey
- [x] Key
- [x] MouseButton
- [x] MouseCursorEvent
- [x] MouseRelativeEvent
- [x] MouseScrollEvent
- [x] RenderArgs
- [x] RenderEvent
- [x] ResizeArgs
- [x] ResizeEvent
- [x] TextEvent
- [x] Touch
- [x] TouchArgs
- [x] TouchEvent
- [x] UpdateArgs
- [x] UpdateEvent
- [x] TimeStamp
