### ISSUE TITLE
Stability tracking issue for pistoncore-window

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1355]
- [x] Api (stabilized in piston-graphics_api_version)
- [x] UnsupportedGraphicsApiError (stabilized in piston-graphics_api_version)
- [x] ProcAddress
- [x] Size
- [x] Size::width
- [x] Size::height
- [x] Position
- [x] Position::x
- [x] Position::y
- [x] OpenGlWindow
- [x] OpenGlWindow::get_proc_address
- [x] OpenGlWindow::is_current
- [x] OpenGlWindow::make_current
- [x] Window
- [x] Window::set_window_should_close
- [x] Window::should_close
- [x] Window::size
- [x] Window::swap_buffers
- [x] Window::wait_event
- [x] Window::wait_event_timeout
- [x] Window::poll_event
- [x] Window::draw_size
- [x] AdvancedWindow
- [x] AdvancedWindow::get_title
- [x] AdvancedWindow::set_title
- [x] AdvancedWindow::get_exit_on_esc
- [x] AdvancedWindow::set_exit_on_esc
- [x] AdvancedWindow::get_automatic_close
- [x] AdvancedWindow::set_automatic_close
- [x] AdvancedWindow::set_capture_cursor
- [x] AdvancedWindow::show
- [x] AdvancedWindow::hide
- [x] AdvancedWindow::get_position
- [x] AdvancedWindow::set_position
- [x] AdvancedWindow::set_size
- [x] AdvancedWindow::title
- [x] AdvancedWindow::exit_on_esc
- [x] AdvancedWindow::automatic_close
- [x] AdvancedWindow::capture_cursor
- [x] AdvancedWindow::position
- [x] WindowSettings
- [x] WindowSettings::new
- [x] WindowSettings::build
- [x] WindowSettings::get_title
- [x] WindowSettings::set_title
- [x] WindowSettings::title
- [x] WindowSettings::get_size
- [x] WindowSettings::set_size
- [x] WindowSettings::size
- [x] WindowSettings::get_fullscreen
- [x] WindowSettings::set_fullscreen
- [x] WindowSettings::fullscreen
- [x] WindowSettings::get_exit_on_esc
- [x] WindowSettings::set_exit_on_esc
- [x] WindowSettings::exit_on_esc
- [x] WindowSettings::get_automatic_close
- [x] WindowSettings::set_automatic_close
- [x] WindowSettings::automatic_close
- [x] WindowSettings::get_samples
- [x] WindowSettings::set_samples
- [x] WindowSettings::samples
- [x] WindowSettings::get_vsync
- [x] WindowSettings::set_vsync
- [x] WindowSettings::vsync
- [x] WindowSettings::get_maybe_graphics_api
- [x] WindowSettings::set_maybe_graphics_api
- [x] WindowSettings::maybe_graphics_api
- [x] WindowSettings::set_graphics_api
- [x] WindowSettings::graphics_api
- [x] WindowSettings::get_srgb
- [x] WindowSettings::set_srgb
- [x] WindowSettings::srgb
- [x] WindowSettings::get_resizable
- [x] WindowSettings::set_resizable
- [x] WindowSettings::resizable
- [x] WindowSettings::get_decorated
- [x] WindowSettings::set_decorated
- [x] WindowSettings::decorated
- [x] WindowSettings::get_controllers
- [x] WindowSettings::set_controllers
- [x] WindowSettings::controllers
- [x] WindowSettings::get_transparent
- [x] WindowSettings::set_transparent
- [x] WindowSettings::transparent
- [x] BuildFromWindowSettings
- [x] UnsupportedGraphicsApiError
